---
-  name: Configure Web VM with Docker
   hosts: webservers
   become: true
   tasks:

   -  name: docker.io
      apt:
        update_cashe: yes
        name: docker.io
        state: present

    -  name: Install pip3
       apt:
         name: python-pip
         state: present
        
    -  name: Install Python Docker Module
       pip:
         name: docker
         state: present

    -  name: downlod and launch a docker web container
       docker_container:
          name: dvwq
          image: cyberxsecurity/dvwa
          state: started
          restart_policy: always
          published_ports: 80:80
    -  name: Enable docker service
       systemd:
         name: docker
         enabled: yes